main2: main2.c count_mutual_links2.c read_graph_from_file2.c top_n_webpages.c
	gcc main2.c count_mutual_links2.c read_graph_from_file2.c top_n_webpages.c -I.
	./a.out web-NotreDame.txt

main1: count_mutual_links1.c read_graph_from_file1.c top_n_webpages.c
	gcc count_mutual_links1.c read_graph_from_file1.c top_n_webpages.c -I.
	./a.out test.txt